name: deploy

on:
  # During debug
  pull_request:
  push:
    branches: [ main ]

env:
  TF_PLUGIN_CACHE_DIR: ${{ github.workspace }}/.terraform.d/plugin-cache
  TF_IN_AUTOMATION: true

jobs:
  plan-prod:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Set up Terraform"
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.1
          cli_config_credentials_token: ${{ secrets.TERRAFORM_CLOUD_TEAM_TOKEN }}

      - name: "Activate workspace"
        run: terraform workspace select prod

      - name: "Restore Terraform plugin cache"
        uses: actions/cache@v2
        with:
          path: ${{ env.TF_PLUGIN_CACHE_DIR }}
          key: terraform-providers-${{ hashFiles('.terraform.lock.hcl') }}
          restore-keys: |
            terraform-providers-

      - name: "terraform init"
        run: terraform init --input=false

      - name: "terraform plan"
        run: terraform plan --out tfplan --input=false
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_PROD_SA_KEY_JSON }}

      - name: "Upload tfplan for use in deploy job"
        uses: actions/upload-artifact@v2
        with:
          name: tfplan-prod
          path: tfplan

  deploy-prod:
    runs-on: ubuntu-latest
    needs: [ plan-prod ]
    environment: prod
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Set up Terraform"
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.1
          cli_config_credentials_token: ${{ secrets.TERRAFORM_CLOUD_TEAM_TOKEN }}

      - name: "Activate workspace"
        run: terraform workspace select prod

      - name: "Restore Terraform plugin cache"
        uses: actions/cache@v2
        with:
          path: ${{ env.TF_PLUGIN_CACHE_DIR }}
          key: terraform-providers-${{ hashFiles('.terraform.lock.hcl') }}
          restore-keys: |
            terraform-providers-

      - name: "terraform init"
        run: terraform init --input=false

      - name: "Download tfplan from plan job"
        uses: actions/download-artifact@v2
        with:
          name: tfplan-prod

      - name: "terraform apply"
        run: terraform apply tfplan --input=false
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_PROD_SA_KEY }}
