name: dev-deploy

on:
  pull_request:
    types: [converted_to_draft, closed]

env:
  TF_IN_AUTOMATION: true
  TF_ORGANIZATION_NAME: "shortcake"
  TF_PLUGIN_CACHE_DIR: ${{ github.workspace }}/.terraform.d/plugin-cache
  TF_WORKSPACE_PREFIX: "shortcake"
  TF_VERSION: 1.0.1

jobs:
  dev-workspace-exists:
    name: "Check if workspace exists"
    runs-on: ubuntu-latest
    outputs:
      workspace-name: ${{ steps.workspace-name.outputs.workspace-name }}
      workspace-exists: ${{ steps.workspace-exists.outputs.workspace-exists }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Get workspace name"
        id: workspace-name
        shell: python
        run: |
          pr_number = "${{ github.event.number }}"
          workspace_name = f"dev-pr{pr_number}"

          print(f"Workspace name: {workspace_name}")
          print(f"::set-output name=workspace-name::{workspace_name}")

      - name: "Set up Terraform"
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VERSION }}
          cli_config_credentials_token: ${{ secrets.TERRAFORM_CLOUD_TEAM_TOKEN }}

      - name: "Create plugin cache dir"
        run: mkdir -p ${{ env.TF_PLUGIN_CACHE_DIR }}

      - name: "Restore Terraform plugin cache"
        uses: actions/cache@v2
        with:
          path: ${{ env.TF_PLUGIN_CACHE_DIR }}
          key: terraform-providers-${{ hashFiles('.terraform.lock.hcl') }}
          restore-keys: |
            terraform-providers-

        # This needs to be done before selecting/creating workspace
      - name: "Terraform init"
        # This throws an error about unsupported workspaces for some reason
        continue-on-error: true
        run: terraform init --input=false

      - name: "Check if workspace exists"
        id: workspace-exists
        run: |
          if terraform workspace select ${WORKSPACE_NAME} ; then
              WORKSPACE_EXISTS=true
          else
              WORKSPACE_EXISTS=false
          fi

          echo "Workspace ${WORKSPACE_NAME} exists: ${WORKSPACE_EXISTS}
          echo "::set-output name=workspace-exists::${WORKSPACE_EXISTS}"
        env:
          WORKSPACE_NAME: ${{ steps.workspace-name.outputs.workspace-name }}

  dev-destroy-plan:
    name: "Terraform destroy plan"
    runs-on: ubuntu-latest
    environment: dev-plan
    needs: [ dev-workspace-exists ]
    if: ${{ needs.dev-workspace-exists.outputs.workspace-exists == 'true' }}
    outputs:
      resources-to-destroy: ${{ steps.resources-to-destroy.outputs.resources-to-destroy }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Set up Terraform"
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VERSION }}
          cli_config_credentials_token: ${{ secrets.TERRAFORM_CLOUD_TEAM_TOKEN }}

      - name: "Create plugin cache dir"
        run: mkdir -p ${{ env.TF_PLUGIN_CACHE_DIR }}

      - name: "Restore Terraform plugin cache"
        uses: actions/cache@v2
        with:
          path: ${{ env.TF_PLUGIN_CACHE_DIR }}
          key: terraform-providers-${{ hashFiles('.terraform.lock.hcl') }}
          restore-keys: |
            terraform-providers-

      - name: "Terraform init"
        run: terraform init --input=false
        env:
          # https://support.hashicorp.com/hc/en-us/articles/360043550953
          TF_WORKSPACE: ${{ needs.dev-workspace-exists.outputs.workspace-name }}

      - name: "Activate workspace"
        run: terraform workspace select ${{ needs.dev-workspace-exists.outputs.workspace-name }}

      - name: "Terraform plan"
        id: destroy-plan
        # https://github.com/hashicorp/terraform/issues/29130
        continue-on-error: true
        run: terraform plan --destroy --input=false --out=tfplan --detailed-exitcode
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_DEV_PLAN_SA_KEY_JSON }}
          TF_VAR_deployment_name: "pr${{ github.event.number }}"

      - name: "Check for changes in Terraform plan"
        id: resources-to-destroy
        shell: python
        run: |
          import sys

          exit_code = ${{ steps.plan.outputs.exitcode }}
          print(f"Exit code = {exit_code}")

          if exit_code == 0:
              plan_has_changes = "false"
          elif exit_code == 2:
              plan_has_changes = "true"
          else:
              sys.exit(exit_code)

          print(f"Plan has changes: {plan_has_changes}")
          print(f"::set-output name=resources-to-destroy::{plan_has_changes}")

      - name: "Upload tfplan for use in deploy job"
        uses: actions/upload-artifact@v2
        with:
          name: tfplan
          path: tfplan

  dev-destroy:
    name: "Destroy workspace"
    environment: dev-destroy
    runs-on: ubuntu-latest
    needs: [ dev-workspace-exists, dev-destroy-plan ]
    if: ${{ needs.dev-destroy-plan.outputs.resources-to-destroy == 'true' }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Set up Terraform"
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VERSION }}
          cli_config_credentials_token: ${{ secrets.TERRAFORM_CLOUD_TEAM_TOKEN }}

      - name: "Restore Terraform plugin cache"
        uses: actions/cache@v2
        with:
          path: ${{ env.TF_PLUGIN_CACHE_DIR }}
          key: terraform-providers-${{ hashFiles('.terraform.lock.hcl') }}
          restore-keys: |
            terraform-providers-

      - name: "Terraform init"
        run: terraform init --input=false
        env:
          # https://support.hashicorp.com/hc/en-us/articles/360043550953
          TF_WORKSPACE: ${{ needs.dev-workspace-exists.outputs.workspace-name }}

      - name: "Activate workspace"
        run: terraform workspace select ${{ needs.dev-workspace-exists.outputs.workspace-name }}

      - name: "Download tfplan from plan job"
        uses: actions/download-artifact@v2
        with:
          name: tfplan

      - name: "Terraform destroy"
        run: terraform destroy --input=false tfplan
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_DEV_DEPLOY_SA_KEY_JSON }}

  dev-delete:
    name: "Delete workspace"
    environment: dev-destroy
    runs-on: ubuntu-latest
    needs: [ dev-workspace-exists, dev-destroy ]
    # The always() is here to make this step run even if dev-destroy is skipped
    if: always() && ${{ needs.dev-workspace-exists.outputs.dev-workspace-exists == 'true' }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Set up Terraform"
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VERSION }}
          cli_config_credentials_token: ${{ secrets.TERRAFORM_CLOUD_TEAM_TOKEN }}

      - name: "Restore Terraform plugin cache"
        uses: actions/cache@v2
        with:
          path: ${{ env.TF_PLUGIN_CACHE_DIR }}
          key: terraform-providers-${{ hashFiles('.terraform.lock.hcl') }}
          restore-keys: |
            terraform-providers-

      - name: "Terraform init"
        run: terraform init --input=false
        env:
          # https://support.hashicorp.com/hc/en-us/articles/360043550953
          TF_WORKSPACE: ${{ needs.dev-workspace-exists.outputs.workspace-name }}

      - name: "Assert that destroy would do nothing"
        run: terraform plan --destroy --input=false --detailed-exitcode
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_DEV_PLAN_SA_KEY_JSON }}
          TF_VAR_deployment_name: "pr${{ github.event.number }}"

#      - name: "Delete workspace"
#        run: terraform workspace delete ${{ needs.dev-workspace-exists.outputs.workspace-name }}
