name: infra-dev-deploy

on:
  pull_request:
    types: [synchronize, reopened, opened, ready_for_review]

jobs:
  infra-dev-deploy:
    uses: shortcake-dev/shortcake-terraform/.github/workflows/tf-deploy.yml@d701712512f707152363c27955285c9707737e22
    with:
      release_type: "dev"
      release_name: "infra-pr${{ github.event.number }}"
