name: infra-dev-destroy

on:
  pull_request:
    types: [converted_to_draft, closed]

jobs:
  infra-dev-deploy:
    uses: shortcake-dev/shortcake-terraform/.github/workflows/tf-destroy.yml@d701712512f707152363c27955285c9707737e22
    with:
      release_type: "dev"
      release_name: "infra-pr${{ github.event.number }}"

