name: infra-staging-deploy

on:
  push:
    branches:
      - main

jobs:
  infra-staging-deploy:
    # environment: tf-staging
    uses: ./.github/workflows/tf-deploy.yml
    with:
      release_type: "staging"
      release_name: "infra"
    secrets:
      terraform_org_token: ${{ secrets.TERRAFORM_CLOUD_ORG_TOKEN }}
      terraform_team_token: ${{ secrets.TERRAFORM_CLOUD_TEAM_TOKEN }}
      # google_cloud_plan_token: ${{ secrets.GCP_PLAN_SA_KEY_JSON }}
      # google_cloud_deploy_token: ${{ secrets.GCP_DEPLOY_SA_KEY_JSON }}
      google_cloud_plan_token: ${{ secrets.GCP_PLAN_SA_KEY_JSON__STAGING }}
      google_cloud_deploy_token: ${{ secrets.GCP_DEPLOY_SA_KEY_JSON__STAGING }}
