name: infra-dev-deploy

on:
  pull_request:
    types: [synchronize, reopened, opened, ready_for_review]

jobs:
  infra-dev-deploy:
    # environment: tf-dev
    uses: shortcake-dev/shortcake-terraform/.github/workflows/tf-deploy.yml@da9fb4e4
    with:
      release_type: "dev"
      release_name: "infra-pr${{ github.event.number }}"
      terraform_org_token: ${{ secrets.TERRAFORM_CLOUD_ORG_TOKEN }}
      terraform_team_token: ${{ secrets.TERRAFORM_CLOUD_TEAM_TOKEN }}
      # google_cloud_plan_token: ${{ secrets.GCP_PLAN_SA_KEY_JSON }}
      # google_cloud_deploy_token: ${{ secrets.GCP_DEPLOY_SA_KEY_JSON }}
      google_cloud_plan_token: ${{ secrets.GCP_PLAN_SA_KEY_JSON__STAGING }}
      google_cloud_deploy_token: ${{ secrets.GCP_DEPLOY_SA_KEY_JSON__STAGING }}
