name: infra-dev-destroy

on:
  pull_request:
    types: [converted_to_draft, closed]

jobs:
  infra-dev-destroy:
    # environment: tf-dev
    uses: ./.github/workflows/tf-destroy.yml
    with:
      release_type: "dev"
      release_name: "infra-pr${{ github.event.number }}"
    secrets:
      terraform_team_token: ${{ secrets.TERRAFORM_CLOUD_TEAM_TOKEN }}
      # google_cloud_plan_token: ${{ secrets.GCP_PLAN_SA_KEY_JSON }}
      # google_cloud_deploy_token: ${{ secrets.GCP_DEPLOY_SA_KEY_JSON }}
      google_cloud_plan_token: ${{ secrets.GCP_PLAN_SA_KEY_JSON__DEV }}
      google_cloud_deploy_token: ${{ secrets.GCP_DEPLOY_SA_KEY_JSON__DEV }}
