name: request-dev-deploy
on:
  workflow_dispatch:
    inputs:
      release_name:
        description: "Name/tag of the release"
        required: true
      backend_version:
        description: "Backend version"
        required: false
        default: "latest"

jobs:
  request-deploy:
    # environment: tf-dev
    uses: ./.github/workflows/tf-deploy.yml
    with:
      release_name: ${{ github.event.inputs.release_name }}
      backend_version: ${{ github.event.inputs.backend_version }}
    secrets:
      terraform_org_token: ${{ secrets.TERRAFORM_CLOUD_ORG_TOKEN }}
      terraform_team_token: ${{ secrets.TERRAFORM_CLOUD_TEAM_TOKEN }}
      # google_cloud_plan_token: ${{ secrets.GCP_PLAN_SA_KEY_JSON }}
      # google_cloud_deploy_token: ${{ secrets.GCP_DEPLOY_SA_KEY_JSON }}
      google_cloud_plan_token: ${{ secrets.GCP_PLAN_SA_KEY_JSON__DEV }}
      google_cloud_deploy_token: ${{ secrets.GCP_DEPLOY_SA_KEY_JSON__DEV }}

